#ifndef SCA_FIA_H
#define SCA_FIA_H

#define NO_STAGES 8

#define NO_PROTECTION 0
#define COARSE_SHUFFLING 1
#define GROUP_COARSE_SHUFFLING 2
#define GROUP_SHUFFLING 4
#define FINE_SHUFFLING 8
#define COARSE_MULTIPLICATIVE_MASKING 16
#define FINE_MULTIPLICATIVE_MASKING 32
#define GENERIC_MULTIPLICATIVE_MASKING 64

#define NTT_PROTECTION_MODE GENERIC_MULTIPLICATIVE_MASKING

#define RANDOM_BUFFER_SIZE 4
#define NO_MASKS_IN_STAGE 2

#define VERIFY_AFTER_SIGN 1
#define VERIFY_ADD 1
#define VERIFY_Y_GEN 1
#define PROTECT_VERIFY_COMPARE 1

#endif
