#ifndef SCA_FIA_H
#define SCA_FIA_H

#define RANDOM_BUFFER_SIZE_NEW 256
#define RANDOM_BUFFER_SIZE 4

#define NO_PROTECTION 0
#define COARSE_SHUFFLING 1
#define GROUP_COARSE_SHUFFLING 2
#define GROUP_SHUFFLING 4
#define FINE_SHUFFLING 8
#define COARSE_MULTIPLICATIVE_MASKING 16
#define FINE_MULTIPLICATIVE_MASKING 32
#define GENERIC_MULTIPLICATIVE_MASKING 64
#define NO_MASKS_IN_STAGE 2

#define NTT_PROTECTION_MODE GENERIC_MULTIPLICATIVE_MASKING
#define CT_SANITY_CHECK 1
#define MP_SANITY_CHECK 1
#define PROTECT_COMPARE 1
#define NONCE_FAULT_CHECK 1

#define NO_RAND_CHECK 20
#define FAULT_REPET 10

#define SHUFFLE_ENCODE_DECODE 1

#endif
